package main

import "time"

type User struct {
	Id         string   `json:"id"`
	StaffId    string   `json:"staff_id"`
	Name       string   `json:"name"`
	Phone      string   `json:"phone"`
	Email      string   `json:"email"`
	Tags       []string `json:"tags"`
	UpdateTime string   `json:"update_time"`
	Removed    bool     `json:"-"`
}

// generated by ChatGPT-3.5

var Users = []User{
	{"001", "001", "王明", "123-456-7890", "wangming@example.com", []string{"计算机学院", "2021"}, getTime(), false},
	{"002", "002", "李华", "987-654-3210", "lihua@example.com", []string{"外国语学院", "2022"}, getTime(), false},
	{"003", "003", "张伟", "555-555-5555", "zhangwei@example.com", []string{"电子信息学院", "2023"}, getTime(), false},
	{"004", "004", "刘强", "111-222-3333", "liuqiang@example.com", []string{"法学院", "2021"}, getTime(), false},
	{"005", "005", "陈娜", "444-555-6666", "chenna@example.com", []string{"计算机学院", "2022"}, getTime(), false},
	{"006", "006", "赵刚", "777-888-9999", "zhaogang@example.com", []string{"外国语学院", "2023"}, getTime(), false},
	{"007", "007", "孙静", "333-222-1111", "sunjing@example.com", []string{"电子信息学院", "2021"}, getTime(), false},
	{"008", "008", "周丽", "999-888-7777", "zhouli@example.com", []string{"法学院", "2022"}, getTime(), false},
	{"009", "009", "吴伟", "666-555-4444", "wuwei@example.com", []string{"计算机学院", "2023"}, getTime(), false},
	{"010", "010", "朱敏", "222-333-4444", "zhumin@example.com", []string{"外国语学院", "2021"}, getTime(), false},
	{"011", "011", "刘洋", "888-777-9999", "liuyang@example.com", []string{"电子信息学院", "2022"}, getTime(), false},
	{"012", "012", "徐杰", "111-111-1111", "xujie@example.com", []string{"法学院", "2023"}, getTime(), false},
	{"013", "013", "陈霞", "444-444-4444", "chenxia@example.com", []string{"计算机学院", "2021"}, getTime(), false},
	{"014", "014", "王刚", "777-777-7777", "wanggang@example.com", []string{"外国语学院", "2022"}, getTime(), false},
	{"015", "015", "李秀", "222-222-2222", "lixiu@example.com", []string{"电子信息学院", "2023"}, getTime(), false},
	{"016", "016", "张辉", "333-333-3333", "zhanghui@example.com", []string{"法学院", "2021"}, getTime(), false},
	{"017", "017", "赵婷", "555-555-5555", "zhaoting@example.com", []string{"计算机学院", "2022"}, getTime(), false},
	{"018", "018", "黄强", "666-666-6666", "huangqiang@example.com", []string{"外国语学院", "2023"}, getTime(), false},
	{"019", "019", "周丽", "888-888-8888", "zhouli@example.com", []string{"电子信息学院", "2021"}, getTime(), false},
	{"020", "020", "李红", "111-111-1111", "lihong@example.com", []string{"法学院", "2022"}, getTime(), false},
	{"021", "021", "李明", "222-222-2222", "liming@example.com", []string{"计算机学院", "2023"}, getTime(), false},
	{"022", "022", "刘丽", "333-333-3333", "liuli@example.com", []string{"外国语学院", "2021"}, getTime(), false},
	{"023", "023", "王杰", "444-444-4444", "wangjie@example.com", []string{"电子信息学院", "2022"}, getTime(), false},
	{"024", "024", "陈洋", "555-555-5555", "chenyang@example.com", []string{"法学院", "2023"}, getTime(), false},
	{"025", "025", "刘明", "666-666-6666", "liuming@example.com", []string{"计算机学院", "2021"}, getTime(), false},
	{"026", "026", "王霞", "777-777-7777", "wangxia@example.com", []string{"外国语学院", "2022"}, getTime(), false},
	{"027", "027", "张伟", "888-888-8888", "zhangwei@example.com", []string{"电子信息学院", "2023"}, getTime(), false},
	{"028", "028", "李丽", "999-999-9999", "lili@example.com", []string{"法学院", "2021"}, getTime(), false},
	{"029", "029", "赵强", "000-000-0000", "zhaoqiang@example.com", []string{"计算机学院", "2022"}, getTime(), false},
	{"030", "030", "孙静", "123-123-1234", "sunjing@example.com", []string{"外国语学院", "2023"}, getTime(), false},
	{"031", "031", "王明", "123-456-7890", "wangming@example.com", []string{"计算机学院", "2021"}, getTime(), false},
	{"032", "032", "李华", "987-654-3210", "lihua@example.com", []string{"外国语学院", "2022"}, getTime(), false},
	{"033", "033", "张伟", "555-555-5555", "zhangwei@example.com", []string{"电子信息学院", "2023"}, getTime(), false},
	{"034", "034", "刘强", "111-222-3333", "liuqiang@example.com", []string{"法学院", "2021"}, getTime(), false},
	{"035", "035", "陈娜", "444-555-6666", "chenna@example.com", []string{"计算机学院", "2022"}, getTime(), false},
	{"036", "036", "赵刚", "777-888-9999", "zhaogang@example.com", []string{"外国语学院", "2023"}, getTime(), false},
	{"037", "037", "孙静", "333-222-1111", "sunjing@example.com", []string{"电子信息学院", "2021"}, getTime(), false},
	{"038", "038", "周丽", "999-888-7777", "zhouli@example.com", []string{"法学院", "2022"}, getTime(), false},
	{"039", "039", "吴伟", "666-555-4444", "wuwei@example.com", []string{"计算机学院", "2023"}, getTime(), false},
	{"040", "040", "朱敏", "222-333-4444", "zhumin@example.com", []string{"外国语学院", "2021"}, getTime(), false},
	{"041", "041", "刘洋", "888-777-9999", "liuyang@example.com", []string{"电子信息学院", "2022"}, getTime(), false},
	{"042", "042", "徐杰", "111-111-1111", "xujie@example.com", []string{"法学院", "2023"}, getTime(), false},
	{"043", "043", "陈霞", "444-444-4444", "chenxia@example.com", []string{"计算机学院", "2021"}, getTime(), false},
	{"044", "044", "王刚", "777-777-7777", "wanggang@example.com", []string{"外国语学院", "2022"}, getTime(), false},
	{"045", "045", "李秀", "222-222-2222", "lixiu@example.com", []string{"电子信息学院", "2023"}, getTime(), false},
	{"046", "046", "张辉", "333-333-3333", "zhanghui@example.com", []string{"法学院", "2021"}, getTime(), false},
	{"047", "047", "赵婷", "555-555-5555", "zhaoting@example.com", []string{"计算机学院", "2022"}, getTime(), false},
}

func getTime() string {
	return time.Now().Format(time.DateTime)
}

var backup = make([]User, len(Users))

func init() {
	copy(backup, Users)
}
